import os

# Fast2SMS
FAST2SMS_API_KEY = os.getenv('FAST2SMS_API_KEY')

# Gemini
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Firebase
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH')
FIREBASE_DATABASE_URL = os.getenv('FIREBASE_DATABASE_URL')
